{% set name = "TexSoup" %}
{% set version = "0.1.3" %}
{% set sha256 = "31a27b6f971c927bc0f146ebca7ea7c92077dff173d0d36538cbbd010de8237c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - TexSoup
    - TexSoup.tex


about:
  home: https://github.com/alvinwan/TexSoup
  license: BSD-2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: |
    Parses valid LaTeX and provides a variety of BeautifulSoup-esque methods and
    Pythonic idioms for iterating and searching the parse tree.

extra:
  recipe-maintainers:
    - scopatz
