travis:
  secure:
    BINSTAR_TOKEN: GwgPHl7UE3tEARwRDIuYbO9qxPUYVQHkjw8KHF+LI6fv9eRT6nf1/dSG7MXHgfs7Y3qEu6UB7yw8cX2mT+SuhVEJIC46ukM8DuItPA71Zw2b+YVUDalInmpjQHv5JmfmJd8DoEEiNBqvQ4+dZkqcVez9W8Gmv6iT7bTvZVHWGrJ+m+cJB4tVj/GfyU3wqptpfP86w7quk0zsKNQWj2a7k5arG+6WLJkGNTzEDBTxBkqt4vc48QICNIpu+gjub3ru1WLtx3RJUKBhLJwpD+17Xf5kUratpRt1qmCppkKnuunEcb+isOD65GwNI+rOblZq/tUVdpDk4P2tGbCkEEP8sf57YVGFRq0mMt+0WVEOXI5rAkpG8CaZyFrO8Rg7dwKApJeh+PH2MF0LgzWs25QuaWTS/qiKOWqbAWFcT7pCNqXG5YGNLs/gi9OShDW1UkiEoqa1mOJMiaWgNgrV9C0MLHLx+UOrnrkqIs4sDXblYxHB8z1Cn35AG0sRTX3oO2NPyU2SiqAW/sj/BwTonFlY3DIQsSHnl8MZ++nPi/HwRwLeKBmWRJHIdQo+o50q63YuneNhEU9gjYmh8Mabon2jio+tzRXpRSq2o0jAt6qIDprlk3Rs7HAIgKTZuao15NDTxYMTgqg6DYjphu71BpZI1xlA8At4WETMerhTP2QSDmY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
